name: Pawn check
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  check:
    uses: pawnkit/pawn-actions/.github/workflows/pawn-check.yml@v1
    with:
      pawn-version: 1.34.14
      download-url: https://github.com/pawnkit/pawnkit-cli/releases/download/v1.34.14/pawn-linux-amd64.tar.gz
      sha256: 8e3004a689f9ef62a46bc5e108b045b133550bdb1769e951b6f41601c1c0b98a
