name: Pawn
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  check:
    uses: pawnkit/pawn-actions/.github/workflows/pawn-check.yml@v1
    with:
      pawn-version: 1.34.13
      download-url: https://github.com/pawnkit/pawnkit-cli/releases/download/v1.34.13/pawn-linux-amd64.tar.gz
      sha256: b147f1423449c016570f819a81e4073464d19f87c2980121af75724e7f85e9e8
